//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Content {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Content() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Content", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here..
        /// </summary>
        internal static string AccessInvalid_Alert_Index_LoginLink {
            get {
                return ResourceManager.GetString("AccessInvalid_Alert_Index_LoginLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no access to view this url.  To go back home click .
        /// </summary>
        internal static string AccessInvalid_Alert_Message {
            get {
                return ResourceManager.GetString("AccessInvalid_Alert_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry..
        /// </summary>
        internal static string AccessInvalid_Alert_Strong {
            get {
                return ResourceManager.GetString("AccessInvalid_Alert_Strong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Access.
        /// </summary>
        internal static string AccessInvalid_Header1 {
            get {
                return ResourceManager.GetString("AccessInvalid_Header1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html xmlns=&apos;http://www.w3.org/1999/xhtml&apos;&gt;&lt;head&gt;&lt;title&gt;&lt;/title&gt;&lt;style&gt;td{ border: 1px solid black; }&lt;/style&gt;&lt;/head&gt;&lt;body&gt;&lt;br /&gt;&lt;h2&gt;Assist Password&lt;/h2&gt;&lt;br /&gt;&lt;div style = &apos;border-top:3px solid #22BCE5&apos;&gt;&amp;nbsp;&lt;/div&gt;&lt;span style = &apos;font-family:Arial;font-size:10pt&apos;&gt;Hello &lt;b&gt;{FirstName}&lt;/b&gt;,&lt;br /&gt;&lt;br /&gt;&lt;p&gt;Your account details for the Convergys Assist website are as follows:&lt;/p&gt;&lt;br /&gt;&lt;table cellspacing=&apos;0&apos;&gt;&lt;tr&gt;&lt;td&gt;Email Address&lt;/td&gt;&lt;td&gt;{EmailAddress}&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;Password&lt;/td&gt;&lt;td&gt;{Password}&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Assist_EmailBody_NewPassword {
            get {
                return ResourceManager.GetString("Assist_EmailBody_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Callback_Search_Bread1 {
            get {
                return ResourceManager.GetString("Callback_Search_Bread1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Callback Search.
        /// </summary>
        internal static string Callback_Search_Bread2 {
            get {
                return ResourceManager.GetString("Callback_Search_Bread2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Callback_Search_ButtonClear {
            get {
                return ResourceManager.GetString("Callback_Search_ButtonClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Callback_Search_ButtonReset {
            get {
                return ResourceManager.GetString("Callback_Search_ButtonReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Callback_Search_ButtonSearch {
            get {
                return ResourceManager.GetString("Callback_Search_ButtonSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this callback?.
        /// </summary>
        internal static string Callback_Search_DeleteConfirm {
            get {
                return ResourceManager.GetString("Callback_Search_DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Filters.
        /// </summary>
        internal static string Callback_Search_FilterPanelTitle {
            get {
                return ResourceManager.GetString("Callback_Search_FilterPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled From.
        /// </summary>
        internal static string Callback_Search_FilterSchedFLabel {
            get {
                return ResourceManager.GetString("Callback_Search_FilterSchedFLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword.
        /// </summary>
        internal static string Callback_Search_FilterSchedKeyLabel {
            get {
                return ResourceManager.GetString("Callback_Search_FilterSchedKeyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled To.
        /// </summary>
        internal static string Callback_Search_FilterSchedTLabel {
            get {
                return ResourceManager.GetString("Callback_Search_FilterSchedTLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Callback_Search_FilterStatusLabel {
            get {
                return ResourceManager.GetString("Callback_Search_FilterStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Callback_Search_Header1 {
            get {
                return ResourceManager.GetString("Callback_Search_Header1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Callback Logs.
        /// </summary>
        internal static string Callback_Search_Header1Small {
            get {
                return ResourceManager.GetString("Callback_Search_Header1Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Callback_Settings_Header1 {
            get {
                return ResourceManager.GetString("Callback_Settings_Header1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for Callback.
        /// </summary>
        internal static string Callback_Settings_Header1small {
            get {
                return ResourceManager.GetString("Callback_Settings_Header1small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Callback Reason.
        /// </summary>
        internal static string Callback_Settings_PanelReason {
            get {
                return ResourceManager.GetString("Callback_Settings_PanelReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent Start Time.
        /// </summary>
        internal static string Callback_Show_AgentTimeStartComp {
            get {
                return ResourceManager.GetString("Callback_Show_AgentTimeStartComp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent Time Zone.
        /// </summary>
        internal static string Callback_Show_AgentTimeZone {
            get {
                return ResourceManager.GetString("Callback_Show_AgentTimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned Agent.
        /// </summary>
        internal static string Callback_Show_AssignToAgent {
            get {
                return ResourceManager.GetString("Callback_Show_AssignToAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enforce schedule?.
        /// </summary>
        internal static string Callback_Show_AssignToSchedEnforce {
            get {
                return ResourceManager.GetString("Callback_Show_AssignToSchedEnforce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned Team.
        /// </summary>
        internal static string Callback_Show_AssignToTeam {
            get {
                return ResourceManager.GetString("Callback_Show_AssignToTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Number.
        /// </summary>
        internal static string Callback_Show_CallRefNum {
            get {
                return ResourceManager.GetString("Callback_Show_CallRefNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example: External Host ID.
        /// </summary>
        internal static string Callback_Show_CallRefNumP {
            get {
                return ResourceManager.GetString("Callback_Show_CallRefNumP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string Callback_Show_Comments {
            get {
                return ResourceManager.GetString("Callback_Show_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact 1.
        /// </summary>
        internal static string Callback_Show_Contact1 {
            get {
                return ResourceManager.GetString("Callback_Show_Contact1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example: Mobile.
        /// </summary>
        internal static string Callback_Show_Contact1P {
            get {
                return ResourceManager.GetString("Callback_Show_Contact1P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact 2.
        /// </summary>
        internal static string Callback_Show_Contact2 {
            get {
                return ResourceManager.GetString("Callback_Show_Contact2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example: Home.
        /// </summary>
        internal static string Callback_Show_Contact2P {
            get {
                return ResourceManager.GetString("Callback_Show_Contact2P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        internal static string Callback_Show_CustName {
            get {
                return ResourceManager.GetString("Callback_Show_CustName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Start Time.
        /// </summary>
        internal static string Callback_Show_CustTimeStartComp {
            get {
                return ResourceManager.GetString("Callback_Show_CustTimeStartComp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Time Zone.
        /// </summary>
        internal static string Callback_Show_CustTimeZone {
            get {
                return ResourceManager.GetString("Callback_Show_CustTimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Callback_Show_DateComp {
            get {
                return ResourceManager.GetString("Callback_Show_DateComp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Callback.
        /// </summary>
        internal static string Callback_Show_Header1 {
            get {
                return ResourceManager.GetString("Callback_Show_Header1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduler.
        /// </summary>
        internal static string Callback_Show_Header1Small {
            get {
                return ResourceManager.GetString("Callback_Show_Header1Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        internal static string Callback_Show_Reason {
            get {
                return ResourceManager.GetString("Callback_Show_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        internal static string Callback_Show_Reason1 {
            get {
                return ResourceManager.GetString("Callback_Show_Reason1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Callback_Show_StatusLabel {
            get {
                return ResourceManager.GetString("Callback_Show_StatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        internal static string Callback_Show_Team {
            get {
                return ResourceManager.GetString("Callback_Show_Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time.
        /// </summary>
        internal static string Callback_Show_TimeEndComp {
            get {
                return ResourceManager.GetString("Callback_Show_TimeEndComp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oh snap!  Something went wrong....
        /// </summary>
        internal static string Error_Index_Alert_Strong {
            get {
                return ResourceManager.GetString("Error_Index_Alert_Strong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error_Index_Header1 {
            get {
                return ResourceManager.GetString("Error_Index_Header1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here..
        /// </summary>
        internal static string Error_Index_LoginLink {
            get {
                return ResourceManager.GetString("Error_Index_LoginLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start over again .
        /// </summary>
        internal static string Error_Index_Message {
            get {
                return ResourceManager.GetString("Error_Index_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Offline_Search_Bread1 {
            get {
                return ResourceManager.GetString("Offline_Search_Bread1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Callback Search.
        /// </summary>
        internal static string Offline_Search_Bread2 {
            get {
                return ResourceManager.GetString("Offline_Search_Bread2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Offline_Search_ButtonClear {
            get {
                return ResourceManager.GetString("Offline_Search_ButtonClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Offline_Search_ButtonReset {
            get {
                return ResourceManager.GetString("Offline_Search_ButtonReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Offline_Search_ButtonSearch {
            get {
                return ResourceManager.GetString("Offline_Search_ButtonSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this offline activity?.
        /// </summary>
        internal static string Offline_Search_DeleteConfirm {
            get {
                return ResourceManager.GetString("Offline_Search_DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Filters.
        /// </summary>
        internal static string Offline_Search_FilterPanelTitle {
            get {
                return ResourceManager.GetString("Offline_Search_FilterPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string Offline_Search_FilterSchedFLabel {
            get {
                return ResourceManager.GetString("Offline_Search_FilterSchedFLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword.
        /// </summary>
        internal static string Offline_Search_FilterSchedKeyLabel {
            get {
                return ResourceManager.GetString("Offline_Search_FilterSchedKeyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string Offline_Search_FilterSchedTLabel {
            get {
                return ResourceManager.GetString("Offline_Search_FilterSchedTLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Offline_Search_FilterStatusLabel {
            get {
                return ResourceManager.GetString("Offline_Search_FilterStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        internal static string Offline_Search_Header1 {
            get {
                return ResourceManager.GetString("Offline_Search_Header1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities.
        /// </summary>
        internal static string Offline_Search_Header1Small {
            get {
                return ResourceManager.GetString("Offline_Search_Header1Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Offline_Settings_Header1 {
            get {
                return ResourceManager.GetString("Offline_Settings_Header1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for Offline.
        /// </summary>
        internal static string Offline_Settings_Header1small {
            get {
                return ResourceManager.GetString("Offline_Settings_Header1small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Types.
        /// </summary>
        internal static string Offline_Settings_PanelActivity {
            get {
                return ResourceManager.GetString("Offline_Settings_PanelActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Types.
        /// </summary>
        internal static string Offline_Settings_PanelContact {
            get {
                return ResourceManager.GetString("Offline_Settings_PanelContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Type.
        /// </summary>
        internal static string Offline_Show_ActivityType {
            get {
                return ResourceManager.GetString("Offline_Show_ActivityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned Agent.
        /// </summary>
        internal static string Offline_Show_AssignToAgent {
            get {
                return ResourceManager.GetString("Offline_Show_AssignToAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned Team.
        /// </summary>
        internal static string Offline_Show_AssignToTeam {
            get {
                return ResourceManager.GetString("Offline_Show_AssignToTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Identity.
        /// </summary>
        internal static string Offline_Show_CaseIdentity {
            get {
                return ResourceManager.GetString("Offline_Show_CaseIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string Offline_Show_Comments {
            get {
                return ResourceManager.GetString("Offline_Show_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Type.
        /// </summary>
        internal static string Offline_Show_ContactType {
            get {
                return ResourceManager.GetString("Offline_Show_ContactType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Comment.
        /// </summary>
        internal static string Offline_Show_EventComments {
            get {
                return ResourceManager.GetString("Offline_Show_EventComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline Events.
        /// </summary>
        internal static string Offline_Show_EventTableLabel {
            get {
                return ResourceManager.GetString("Offline_Show_EventTableLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        internal static string Offline_Show_Header1 {
            get {
                return ResourceManager.GetString("Offline_Show_Header1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        internal static string Offline_Show_Header1Small {
            get {
                return ResourceManager.GetString("Offline_Show_Header1Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Offline_Show_StatusLabel {
            get {
                return ResourceManager.GetString("Offline_Show_StatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New Password.
        /// </summary>
        internal static string Profile_Index_ConfrimPwd {
            get {
                return ResourceManager.GetString("Profile_Index_ConfrimPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        internal static string Profile_Index_EmailAddress {
            get {
                return ResourceManager.GetString("Profile_Index_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Number.
        /// </summary>
        internal static string Profile_Index_EmpNumber {
            get {
                return ResourceManager.GetString("Profile_Index_EmpNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Profile_Index_Header1 {
            get {
                return ResourceManager.GetString("Profile_Index_Header1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daylight Saving Time?.
        /// </summary>
        internal static string Profile_Index_IsDSTLabel {
            get {
                return ResourceManager.GetString("Profile_Index_IsDSTLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title.
        /// </summary>
        internal static string Profile_Index_JobTitle {
            get {
                return ResourceManager.GetString("Profile_Index_JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        internal static string Profile_Index_Manager {
            get {
                return ResourceManager.GetString("Profile_Index_Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        internal static string Profile_Index_NewPwd {
            get {
                return ResourceManager.GetString("Profile_Index_NewPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        internal static string Profile_Index_OldPwd {
            get {
                return ResourceManager.GetString("Profile_Index_OldPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string Profile_Index_PanelHChangePwd {
            get {
                return ResourceManager.GetString("Profile_Index_PanelHChangePwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Default Timezone.
        /// </summary>
        internal static string Profile_Index_PanelHChangeTZ {
            get {
                return ResourceManager.GetString("Profile_Index_PanelHChangeTZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password save failed..
        /// </summary>
        internal static string Profile_Index_PasswordSaveFailed {
            get {
                return ResourceManager.GetString("Profile_Index_PasswordSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password saved successfully..
        /// </summary>
        internal static string Profile_Index_PasswordSaveSuccess {
            get {
                return ResourceManager.GetString("Profile_Index_PasswordSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string Profile_Index_Role {
            get {
                return ResourceManager.GetString("Profile_Index_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        internal static string Profile_Index_Site {
            get {
                return ResourceManager.GetString("Profile_Index_Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        internal static string Profile_Index_Team {
            get {
                return ResourceManager.GetString("Profile_Index_Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timezone save failed..
        /// </summary>
        internal static string Profile_Index_TZSaveFailed {
            get {
                return ResourceManager.GetString("Profile_Index_TZSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timezone saved successfully..
        /// </summary>
        internal static string Profile_Index_TZSaveSuccess {
            get {
                return ResourceManager.GetString("Profile_Index_TZSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Public_Login_ButtonLogin {
            get {
                return ResourceManager.GetString("Public_Login_ButtonLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Password.
        /// </summary>
        internal static string Public_Login_ButtonSendPassword {
            get {
                return ResourceManager.GetString("Public_Login_ButtonSendPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        internal static string Public_Login_CheckBoxRememberMe {
            get {
                return ResourceManager.GetString("Public_Login_CheckBoxRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Public_Login_Header1 {
            get {
                return ResourceManager.GetString("Public_Login_Header1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this is your first time to Convergys Assist and you&apos;re part of the company please use the Send Password feature below..
        /// </summary>
        internal static string Public_Login_Message_Par2 {
            get {
                return ResourceManager.GetString("Public_Login_Message_Par2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        internal static string Public_Login_TexboxEmailAddress {
            get {
                return ResourceManager.GetString("Public_Login_TexboxEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Public_Login_TextboxPassword {
            get {
                return ResourceManager.GetString("Public_Login_TextboxPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Setup.
        /// </summary>
        internal static string Setup_Index_Header1 {
            get {
                return ResourceManager.GetString("Setup_Index_Header1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change User Role.
        /// </summary>
        internal static string Setup_Index_PanelHChangeRole {
            get {
                return ResourceManager.GetString("Setup_Index_PanelHChangeRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role save failed..
        /// </summary>
        internal static string Setup_Index_RoleSaveFailed {
            get {
                return ResourceManager.GetString("Setup_Index_RoleSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role saved successfull..
        /// </summary>
        internal static string Setup_Index_RoleSaveSuccess {
            get {
                return ResourceManager.GetString("Setup_Index_RoleSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        internal static string Setup_Index_Team {
            get {
                return ResourceManager.GetString("Setup_Index_Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Callback.
        /// </summary>
        internal static string _WidgetLeftMenu_ddCallback {
            get {
                return ResourceManager.GetString("_WidgetLeftMenu_ddCallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline Activity.
        /// </summary>
        internal static string _WidgetLeftMenu_ddOffline {
            get {
                return ResourceManager.GetString("_WidgetLeftMenu_ddOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string _WidgetLeftMenu_ddReports {
            get {
                return ResourceManager.GetString("_WidgetLeftMenu_ddReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string _WidgetLeftMenu_lnkCallbackCreate {
            get {
                return ResourceManager.GetString("_WidgetLeftMenu_lnkCallbackCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Callback.
        /// </summary>
        internal static string _WidgetLeftMenu_lnkCallbackNew {
            get {
                return ResourceManager.GetString("_WidgetLeftMenu_lnkCallbackNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string _WidgetLeftMenu_lnkCallbackSearch {
            get {
                return ResourceManager.GetString("_WidgetLeftMenu_lnkCallbackSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string _WidgetLeftMenu_lnkCallbackSettings {
            get {
                return ResourceManager.GetString("_WidgetLeftMenu_lnkCallbackSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string _WidgetLeftMenu_lnkOfflineCreate {
            get {
                return ResourceManager.GetString("_WidgetLeftMenu_lnkOfflineCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Offline Activity.
        /// </summary>
        internal static string _WidgetLeftMenu_lnkOfflineNew {
            get {
                return ResourceManager.GetString("_WidgetLeftMenu_lnkOfflineNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string _WidgetLeftMenu_lnkOfflineSearch {
            get {
                return ResourceManager.GetString("_WidgetLeftMenu_lnkOfflineSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string _WidgetLeftMenu_lnkOfflineSettings {
            get {
                return ResourceManager.GetString("_WidgetLeftMenu_lnkOfflineSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Callback Reports.
        /// </summary>
        internal static string _WidgetLeftMenu_lnkReportsCallback {
            get {
                return ResourceManager.GetString("_WidgetLeftMenu_lnkReportsCallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline Reports.
        /// </summary>
        internal static string _WidgetLeftMenu_lnkReportsOffline {
            get {
                return ResourceManager.GetString("_WidgetLeftMenu_lnkReportsOffline", resourceCulture);
            }
        }
    }
}
