//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Convergys.Assist.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CACallbackEvents
    {
        public int CallbackEventid { get; set; }
        public int CallbackLogId { get; set; }
        public decimal EmpId { get; set; }
        public int EventTypeId { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string Description { get; set; }
        public Nullable<int> ActualEventGraceTimePrior { get; set; }
        public Nullable<int> ActualEventGraceTimePost { get; set; }
    
        public virtual CACallbackLogs CACallbackLogs { get; set; }
    }
}
