//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Convergys.Assist.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAEmployeeView
    {
        public decimal EmpId { get; set; }
        public string EmailAddress { get; set; }
        public string NewPwd { get; set; }
        public Nullable<int> RoleId { get; set; }
        public string FirstName { get; set; }
        public string Team { get; set; }
        public string SiteName { get; set; }
        public string ManagerName { get; set; }
        public string AppEntitlement { get; set; }
        public string JobTitle { get; set; }
        public Nullable<int> TeamId { get; set; }
        public string Timezone { get; set; }
        public Nullable<decimal> HrDifference { get; set; }
        public Nullable<bool> TimeZoneDST { get; set; }
        public Nullable<int> TimeZoneId { get; set; }
        public Nullable<decimal> ManagerId { get; set; }
        public Nullable<int> EmpNumber { get; set; }
        public string SiteAbbreviation { get; set; }
        public Nullable<decimal> SiteId { get; set; }
        public Nullable<int> PermissionId { get; set; }
        public Nullable<int> PreferenceId { get; set; }
    }
}
