//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Convergys.Assist.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CASite
    {
        public CASite()
        {
            this.CAEmployee = new HashSet<CAEmployee>();
            this.CATeam = new HashSet<CATeam>();
        }
    
        public decimal SiteId { get; set; }
        public string SiteName { get; set; }
        public string Location { get; set; }
        public string CountryId { get; set; }
        public string SiteAbbreviation { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<int> SiteOffset { get; set; }
    
        public virtual ICollection<CAEmployee> CAEmployee { get; set; }
        public virtual ICollection<CATeam> CATeam { get; set; }
    }
}
