//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Convergys.Assist.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATeam
    {
        public int TeamId { get; set; }
        public Nullable<decimal> SiteId { get; set; }
        public string Team { get; set; }
    
        public virtual CASite CASite { get; set; }
    }
}
