//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Convergys.Assist.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATeamConfig
    {
        public int TeamConfigID { get; set; }
        public Nullable<int> TeamId { get; set; }
        public Nullable<int> OfflineEventTimePhase1 { get; set; }
        public Nullable<int> OfflineEventTimePhase2 { get; set; }
        public Nullable<int> OfflineEventTimeMax { get; set; }
        public Nullable<int> CallbackLateEmailEnable { get; set; }
        public Nullable<int> CallbackEarlyEmailEnable { get; set; }
        public Nullable<int> CallbackEventGraceTimePrior { get; set; }
        public Nullable<int> CallbackEventGraceTimePost { get; set; }
        public Nullable<int> CallbackMaxLogsPerTimeslot { get; set; }
        public Nullable<int> CallbackMaxScheduleDays { get; set; }
        public Nullable<int> CallbackSchedDataSource { get; set; }
    }
}
