//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketLoadConsole.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TicketLoadConsole.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TicketLoad Command Line Arguments
        ///---------------------------------
        ///
        ////mode:[TEST,DEF]     -mode
        ///                       TEST:  
        ///                           Will put dates on Webtracker
        ///                           Ticket Query guaranteed results.  
        ///                           For dev only
        ///                       DEF:
        ///                           Will let the process run using 
        ///                           default settings.
        ///                           use app.config.
        ///.
        /// </summary>
        internal static string CmdArguments {
            get {
                return ResourceManager.GetString("CmdArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	Doc_Id,
        ///	Contract_Id,
        ///	Client_Name,
        ///	Contract_Status,
        ///	Invit_Freq,
        ///	Send_Email_Invit,
        ///	From_Email,
        ///	Email_Admin,
        ///	Email_Client,
        ///	Domain_Name,
        ///	Strm_FTP_Srvr,
        ///	Strm_FTP_Dir,
        ///	Strm_FTP_Login,
        ///	Strm_FTP_Password,
        ///	Remote_FTP_Host,
        ///	Remote_FTP_Dir,
        ///	Remote_FTP_Login,
        ///	Remote_FTP_Password,
        ///	Input_File_Format,
        ///	Field_Delimiter,
        ///	Last_Processed_File,
        ///	Last_Processed_FileDate,
        ///	Last_Processed_FileIndex,
        ///	Zip1,
        ///	Zip2,
        ///	PGP1,
        ///	PGP2,
        ///	In_Folder,
        ///	Temp_Folder,
        ///	Out_Folder,
        ///	Creat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ESurveyContractFormat {
            get {
                return ResourceManager.GetString("ESurveyContractFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT STRM_TICKETS_SEQ.currval doc_id FROM dual.
        /// </summary>
        internal static string ESurveyGetInsertedIdFormat {
            get {
                return ResourceManager.GetString("ESurveyGetInsertedIdFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO STRM_TICKETS
        ///	(
        ///		CONTRACT_ID,
        ///		TICKET_ID,
        ///		CUSTOMER_ID,
        ///		CUSTOMER_FNAME,
        ///		CUSTOMER_LNAME,
        ///		EMAIL,
        ///		COMPANY,
        ///		PHONE,
        ///		ADDRESS1,
        ///		ADDRESS2,
        ///		CITY,
        ///		STATE,
        ///		ZIP,
        ///		COUNTRY,
        ///		PRODUCT_NAME,
        ///		PRODUCT_CODE,
        ///		PRODUCT_CAT,
        ///		AGENT_ID,
        ///		AGENT_FNAME,
        ///		AGENT_LNAME,
        ///		DATE_SVC_START,
        ///		DATE_SVC_RESOLVE,
        ///		SVC_SHORT_DESC,
        ///		SVC_CAT,
        ///		SVC_SUB_CAT,
        ///		TXT_FLD1,
        ///		TXT_FLD2,
        ///		OTS_MEDIA_ORIGIN,
        ///		OTS_SYSTEM_ORIGIN,
        ///		UCASE_EMAIL,
        ///		AGENT_SITE,
        ///		CUST_LANGUAGE,
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ESurveyInsertTicketFormat {
            get {
                return ResourceManager.GetString("ESurveyInsertTicketFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt; 
        ///	&lt;head&gt; 
        ///		&lt;META HTTP-EQUIV=&quot;Content-Type&quot; CONTENT=&quot;text/html; charset=ISO-8859-1&quot;&gt; 
        ///			&lt;title&gt;Untitled&lt;/title&gt; 
        ///			&lt;style&gt; 
        ///				body.page{ 
        ///				font-family : Arial, Helvetica, sans-serif; 
        ///				font-size : 10pt; 
        ///				} 
        ///				div.divBody{ 
        ///				font-family : Arial, Helvetica, sans-serif; 
        ///				font-size : 8pt; 
        ///				} 
        ///				table.body{ 
        ///				font-family : Arial, Helvetica, sans-serif; 
        ///				font-size : 9pt; 
        ///				} 
        ///			&lt;/style&gt; 
        ///		&lt;/head&gt; 
        ///		&lt;body text=&quot;#000000&quot; bgcolor=&quot;#FFFFFF&quot; leftmargi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ESurveyMessageDutch {
            get {
                return ResourceManager.GetString("ESurveyMessageDutch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt; 
        ///	&lt;head&gt; 
        ///		&lt;META HTTP-EQUIV=&quot;Content-Type&quot; CONTENT=&quot;text/html; charset=ISO-8859-1&quot;&gt; 
        ///			&lt;title&gt;Untitled&lt;/title&gt; 
        ///			&lt;style&gt; 
        ///				body.page{ 
        ///				font-family : Arial, Helvetica, sans-serif; 
        ///				font-size : 10pt; 
        ///				} 
        ///				div.divBody{ 
        ///				font-family : Arial, Helvetica, sans-serif; 
        ///				font-size : 8pt; 
        ///				} 
        ///				table.body{ 
        ///				font-family : Arial, Helvetica, sans-serif; 
        ///				font-size : 9pt; 
        ///				} 
        ///			&lt;/style&gt; 
        ///		&lt;/head&gt; 
        ///		&lt;body text=&quot;#000000&quot; bgcolor=&quot;#FFFFFF&quot; leftmargi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ESurveyMessageEnglish {
            get {
                return ResourceManager.GetString("ESurveyMessageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt; 
        ///	&lt;head&gt; 
        ///		&lt;META HTTP-EQUIV=&quot;Content-Type&quot; CONTENT=&quot;text/html; charset=ISO-8859-1&quot;&gt; 
        ///			&lt;title&gt;Untitled&lt;/title&gt; 
        ///			&lt;style&gt; 
        ///body.page{ 
        ///font-family : Arial, Helvetica, sans-serif; 
        ///font-size : 10pt; 
        ///} 
        ///div.divBody{ 
        ///font-family : Arial, Helvetica, sans-serif; 
        ///font-size : 8pt; 
        ///} 
        ///table.body{ 
        ///font-family : Arial, Helvetica, sans-serif; 
        ///font-size : 9pt; 
        ///} 
        ///			&lt;/style&gt; 
        ///		&lt;/head&gt; 
        ///		&lt;body text=&quot;#000000&quot; bgcolor=&quot;#FFFFFF&quot; leftmargin=10 topmargin=0 marginheight=&quot;0&quot; marginwidth=&quot;0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ESurveyMessageFrench {
            get {
                return ResourceManager.GetString("ESurveyMessageFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt; 
        ///	&lt;head&gt; 
        ///		&lt;META HTTP-EQUIV=&quot;Content-Type&quot; CONTENT=&quot;text/html; charset=ISO-8859-1&quot;&gt; 
        ///			&lt;title&gt;Untitled&lt;/title&gt; 
        ///			&lt;style&gt; 
        ///					body.page{ 
        ///					font-family : Arial, Helvetica, sans-serif; 
        ///					font-size : 10pt; 
        ///					} 
        ///					div.divBody{ 
        ///					font-family : Arial, Helvetica, sans-serif; 
        ///					font-size : 8pt; 
        ///					} 
        ///					table.body{ 
        ///					font-family : Arial, Helvetica, sans-serif; 
        ///					font-size : 9pt; 
        ///					} 
        ///			&lt;/style&gt; 
        ///		&lt;/head&gt; 
        ///		&lt;body text=&quot;#000000&quot; bgcolor=&quot;#FFFFF [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ESurveyMessageGerman {
            get {
                return ResourceManager.GetString("ESurveyMessageGerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	Doc_Id,
        ///	Contract_Id,
        ///	Client_Name,
        ///	Contract_Status,
        ///	Invit_Freq,
        ///	Send_Email_Invit,
        ///	From_Email,
        ///	Email_Admin,
        ///	Email_Client,
        ///	Domain_Name,
        ///	Strm_FTP_Srvr,
        ///	Strm_FTP_Dir,
        ///	Strm_FTP_Login,
        ///	Strm_FTP_Password,
        ///	Remote_FTP_Host,
        ///	Remote_FTP_Dir,
        ///	Remote_FTP_Login,
        ///	Remote_FTP_Password,
        ///	Input_File_Format,
        ///	Field_Delimiter,
        ///	Last_Processed_File,
        ///	Last_Processed_FileDate,
        ///	Last_Processed_FileIndex,
        ///	Zip1,
        ///	Zip2,
        ///	PGP1,
        ///	PGP2,
        ///	In_Folder,
        ///	Temp_Folder,
        ///	Out_Folder,
        ///	Creat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WebTrackerContractFormat {
            get {
                return ResourceManager.GetString("WebTrackerContractFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --WARNING:  THE ORDER OF SELECTED COLUMNS SHOULD NOT BE CHANGED!
        ///select 
        ///l.log_id, 
        ///cu.userid, 
        ///cu.firstname as cust_fname, 
        ///cu.lastname as cust_lname, 
        ///cu.email as cust_email, 
        ///cu.ots_txt_field1 as cust_company, 
        ///cu.phone as cust_phone, 
        ///cu.address1 as cust_addr1, 
        ///cu.address2 as cust_addr2, 
        ///cu.city as cust_city, 
        ///cu.state as cust_state, 
        ///cu.zipcode as cust_zipcode, 
        ///cu.country as cust_country, 
        ///l.ots_product, 
        ///l.ots_platform, 
        ///l.ots_version, 
        ///l.assigned_to as agnt_id, 
        ///ag.firstname as  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WebTrackerTicketFormat {
            get {
                return ResourceManager.GetString("WebTrackerTicketFormat", resourceCulture);
            }
        }
    }
}
