//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowFB.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FFBA_Purchase_History
    {
        public int PurchaseHistoryID { get; set; }
        public Nullable<int> PurchaseProofID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> ByUserID { get; set; }
        public string Comment { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> Completed { get; set; }
    
        public virtual FFBA_Purchase_Proof FFBA_Purchase_Proof { get; set; }
    }
}
