//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowFB.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FFBA_CostCenter
    {
        public int CostCenterID { get; set; }
        public string CostCenterCode { get; set; }
        public string Description { get; set; }
        public int Status { get; set; }
        public int FBProjectId { get; set; }
    }
}
