//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowFB.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FFBA_Purchase_Proof
    {
        public FFBA_Purchase_Proof()
        {
            this.FFBA_Purchase_History = new HashSet<FFBA_Purchase_History>();
        }
    
        public int PurchaseProofID { get; set; }
        public Nullable<int> PurchaseID { get; set; }
        public string DividerName { get; set; }
        public Nullable<System.DateTime> DateFiled { get; set; }
        public Nullable<int> UserFiled { get; set; }
        public string Description { get; set; }
        public string Extension { get; set; }
        public short Status { get; set; }
        public Nullable<int> Pages { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public string Contents { get; set; }
        public string Archive { get; set; }
        public Nullable<int> FileSize { get; set; }
        public Nullable<System.DateTime> LastView { get; set; }
    
        public virtual FFBA_Purchase FFBA_Purchase { get; set; }
        public virtual ICollection<FFBA_Purchase_History> FFBA_Purchase_History { get; set; }
    }
}
