//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowFB.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FFBA_Purchase
    {
        public FFBA_Purchase()
        {
            this.FFBA_Purchase_Proof = new HashSet<FFBA_Purchase_Proof>();
        }
    
        public int PurchaseID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> Status { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
        public Nullable<System.DateTime> Destruction { get; set; }
        public string PurchaseInvoiceNumber { get; set; }
        public string PurchaseInvoiceDescription { get; set; }
        public Nullable<decimal> PurchaseInvoiceTotal { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateStarted { get; set; }
        public string Comment { get; set; }
    
        public virtual FFBA_Projects FFBA_Projects { get; set; }
        public virtual ICollection<FFBA_Purchase_Proof> FFBA_Purchase_Proof { get; set; }
    }
}
