//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Convergys.Assist.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CACallbackEmpBackup
    {
        public int CallbackEmpBackupId { get; set; }
        public int TeamId { get; set; }
        public decimal EmpId { get; set; }
        public decimal BackupEmpId { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
        public Nullable<decimal> ModifiedBy { get; set; }
    }
}
