//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Convergys.Assist.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CACallbackLogsSearchView
    {
        public int CallbackLogId { get; set; }
        public string Team { get; set; }
        public string AssignedTo { get; set; }
        public string LogCreator { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string CustomerName { get; set; }
        public string Contact1Phone { get; set; }
        public string CallReferenceNumber { get; set; }
        public Nullable<int> CallbackStatusId { get; set; }
        public Nullable<System.DateTimeOffset> AgentCallbackTimeStart { get; set; }
        public Nullable<System.DateTimeOffset> AgentCallbackTimeEnd { get; set; }
        public decimal CreatedBy { get; set; }
        public string CallbackReasonType { get; set; }
        public Nullable<bool> TeamActive { get; set; }
        public Nullable<bool> AssignedToActive { get; set; }
        public Nullable<bool> LogCreatorActive { get; set; }
        public Nullable<bool> ReasonTypeActive { get; set; }
        public Nullable<int> TeamId { get; set; }
        public Nullable<decimal> AssignedToEmpId { get; set; }
        public Nullable<decimal> LogCreatorEmpId { get; set; }
    }
}
