//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Convergys.Assist.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CACallbackReasonType
    {
        public int CallbackReasonTypeId { get; set; }
        public string CallbackReasonType { get; set; }
        public Nullable<int> TeamId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
        public Nullable<decimal> ModifiedBy { get; set; }
    }
}
