//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Convergys.Assist.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CACallbackLogs
    {
        public CACallbackLogs()
        {
            this.CACallbackLogHistory = new HashSet<CACallbackLogHistory>();
            this.CACallbackEvents = new HashSet<CACallbackEvents>();
        }
    
        public int CallbackLogId { get; set; }
        public decimal TeamId { get; set; }
        public decimal EmpId { get; set; }
        public decimal CreatedBy { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string CustomerName { get; set; }
        public string Contact1Phone { get; set; }
        public string Contact2Phone { get; set; }
        public string CallReferenceNumber { get; set; }
        public Nullable<decimal> CallbackReasonTypeId { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> CallbackTimeStart { get; set; }
        public Nullable<System.DateTime> CallbackTimeEnd { get; set; }
        public Nullable<decimal> Status { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<decimal> MgrEmailStatus { get; set; }
        public Nullable<int> EarlyEmailStatus { get; set; }
        public Nullable<int> CallbackReasonTypeIdRef { get; set; }
        public Nullable<System.DateTimeOffset> CustomerCallbackTimeStart { get; set; }
        public Nullable<System.DateTimeOffset> CustomerCallbackTimeEnd { get; set; }
        public Nullable<System.DateTimeOffset> AgentCallbackTimeStart { get; set; }
        public Nullable<System.DateTimeOffset> AgentCallbackTimeEnd { get; set; }
        public Nullable<int> CallbackStatusId { get; set; }
        public string EmpName { get; set; }
        public string TeamName { get; set; }
        public string CreatedByName { get; set; }
        public string CallbackReasonTypeText { get; set; }
    
        public virtual ICollection<CACallbackLogHistory> CACallbackLogHistory { get; set; }
        public virtual ICollection<CACallbackEvents> CACallbackEvents { get; set; }
    }
}
