//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Convergys.Assist.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAListEmpTeams
    {
        public decimal EmpID { get; set; }
        public Nullable<int> EmpNumber { get; set; }
        public int TeamID { get; set; }
        public string Team { get; set; }
        public Nullable<decimal> ManagerId { get; set; }
        public string FirstName { get; set; }
        public Nullable<int> RoleId { get; set; }
    }
}
