//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Convergys.Assist.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAPassword
    {
        public int PwId { get; set; }
        public Nullable<decimal> EmpId { get; set; }
        public string OldPwd { get; set; }
        public string NewPwd { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
    
        public virtual CAEmployee CAEmployee { get; set; }
    }
}
