//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Convergys.Assist.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAPreferences
    {
        public int PreferenceId { get; set; }
        public Nullable<decimal> EmpId { get; set; }
        public string Theme { get; set; }
        public string LanguageId { get; set; }
        public Nullable<int> TimeZoneId { get; set; }
        public Nullable<bool> TimeZoneDST { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
        public Nullable<bool> TZConfigured { get; set; }
    }
}
